import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.scss";

const regular = localFont({
  src: "../fonts/HelveticaNowDisplay-Regular.ttf",
  variable: "--regular-font",
});

const bold = localFont({
  src: "../fonts/HelveticaNowDisplay-Bold.ttf",
  variable: "--bold-font",
});

const garamond = localFont({
  src: "../fonts/HelveticaNowDisplay-Bold.ttf",
  variable: "--bold-font",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
